project:
  type: website
  output-dir: docs

website:
  title: "BioEngineering Statistics Spring 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Syllabus.qmd
      - Lecture_1.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

