---
title: "Schedule"
---

### Books and reading materials

#### *Required*

-   [R for Data Science](https://r4ds.hadley.nz). Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund. O'Reilly Press.
-   [Modern Statistics with R](https://www.modernstatisticswithr.com). Måns Thulin, CRC Press.
-   [An Introduction to Statistical Learning](https://www.statlearning.com). James, Witten, Hastie, Tibshirani. Springer

#### *Additional resources*

-   [Modern Statistics for Modern Biology](https://web.stanford.edu/class/bios221/book/). 2019. Holmes and Huber. Cambridge University Press.
-   [ggPlot2: Elegant Graphics for Data Analysis, 3rd Edition](https://ggplot2-book.org). Wickham, Navarro, Pedersen. Springer.
-   [The Visual Display of Quantitative Information.](https://www.amazon.com/Visual-Display-Quantitative-Information/dp/1930824130) Tufte, E.R. Graphics Press, Cheshire CT

### Course schedule

+--------------------------------------------------------------------------+------------------------------------------+-------------+
| Date                                                                     | Topics                                   | Readings    |
+==========================================================================+==========================================+=============+
| 01 April                                                                 | xxxxssssssssssssssssssssssssssssssssssss | xxxx        |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 03 April                                                                 |                                          |             |
|                                                                          |                                          |             |
| ------------------------------------------------------------------------ |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 08 April                                                                 |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 10 April                                                                 |                                          |             |
|                                                                          |                                          |             |
| ------------------------------------------------------------------------ |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 15 April                                                                 |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 17 April                                                                 |                                          |             |
|                                                                          |                                          |             |
| ------------------------------------------------------------------------ |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 22 April                                                                 |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 24 April                                                                 |                                          |             |
|                                                                          |                                          |             |
| ------------------------------------------------------------------------ |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 29 April                                                                 |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 01 May                                                                   |                                          |             |
|                                                                          |                                          |             |
| ------------------------------------------------------------------------ |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 06 May                                                                   |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 08 May                                                                   |                                          |             |
|                                                                          |                                          |             |
| ------------------------------------------------------------------------ |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 13 May                                                                   |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 15 May                                                                   |                                          |             |
|                                                                          |                                          |             |
| ------------------------------------------------------------------------ |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 20 May                                                                   |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 22 May                                                                   |                                          |             |
|                                                                          |                                          |             |
| ------------------------------------------------------------------------ |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 27 May                                                                   |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 29 May                                                                   |                                          |             |
|                                                                          |                                          |             |
| ------------------------------------------------------------------------ |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 3 June                                                                   |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 5 June                                                                   |                                          |             |
|                                                                          |                                          |             |
| ------------------------------------------------------------------------ |                                          |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+
| 10 June                                                                  | FINALS WEEK                              |             |
+--------------------------------------------------------------------------+------------------------------------------+-------------+

