---
title: "Term Long Project - Pulling it All Together"
format: html
editor: visual
---

## Directions

**Assignment:**

Pull together all of the activities that you performed on your own data that you've chosen to analyze throughout the term in association with each homework set and put it into one complete Markdown document that can be rendered.

In addition to packaging these previous analyses together, you can also perform any additional visualizations and analyses that make sense. Lastly, add some interpretive writing that explains the nature of your data, the types of analyses you performed at each step, your outcomes or findings from each, and the conclusions that you might draw from each finding.

The overall goal is to create something like a report to share with a collaborator or your PI, or should your work be far enough along the skeleton of a manuscript that can submitted for subsequent publication.

**Due:** Submit your work via Canvas by the end of the day (midnight) on **Friday, June 13th.** Please submit **both the Quarto_md file *and* the resulting html or pdf file**.

## 
